import type { LesserPanda, KeeperDiary, PandaBlog } from './types'

export const LESSER_PANDAS: LesserPanda[] = [
  {
    id: 'minfa',
    name: 'ミンファ',
    nameEn: 'Minfa',
    gender: 'female',
    birthDate: '2006-06-23',
    birthPlace: '市川市動植物園',
    personality: 'ベテランのお母さん。どっしり落ち着いた存在感がある。',
    favoriteFood: 'タケノコ・バンブーシュート',
    hobby: '日向ぼっこ・昼寝',
    photoUrl: '/pandas/minfa.jpg',
    parentIds: [],
    childrenIds: ['tiara'],
    bio: 'ティアラのお母さん。市川市動植物園から来園した、西山動物園最年長のレッサーパンダ。',
    favoriteCount: 0,
  },
  {
    id: 'kirari',
    name: 'キラリ',
    nameEn: 'Kirari',
    gender: 'female',
    birthDate: '2011-06-27',
    birthPlace: '姫路セントラルパーク',
    personality: 'しっかり者のお母さん。子供たちをいつも見守っている。',
    favoriteFood: 'リンゴ・タケノコ',
    hobby: '毛づくろい・木登り',
    photoUrl: '/pandas/kirari.jpg',
    parentIds: [],
    childrenIds: ['light', 'mocchi'],
    bio: '姫路セントラルパークから来園。ライトとモッチーのお母さん。',
    favoriteCount: 0,
  },
  {
    id: 'taiyo',
    name: 'たいよう',
    nameEn: 'Taiyo',
    gender: 'male',
    birthDate: '2013-06-15',
    birthPlace: '池田動物園',
    personality: '落ち着いた性格。のんびりと過ごすのが好き。',
    favoriteFood: 'バンブーシュート・リンゴ',
    hobby: '木の上でのんびりすること',
    photoUrl: '/pandas/taiyo.png',
    parentIds: [],
    childrenIds: [],
    bio: '池田動物園から婿入りしたオスのパンダ。穏やかな性格で人気者。',
    favoriteCount: 0,
  },
  {
    id: 'light',
    name: 'ライト',
    nameEn: 'Light',
    gender: 'male',
    birthDate: '2013-07-18',
    birthPlace: '鯖江市西山動物園',
    personality: '元気いっぱい。活発に動き回るのが好き。',
    favoriteFood: 'リンゴ・ぶどう',
    hobby: 'ボール遊び・高い所に登ること',
    photoUrl: '/pandas/light.jpg',
    parentIds: ['kirari'],
    childrenIds: ['kaede'],
    partnerId: 'kanoko',
    bio: 'キラリの息子として西山動物園で生まれた。かのこと夫婦でかえでの父。',
    favoriteCount: 0,
  },
  {
    id: 'matsuba',
    name: 'まつば',
    nameEn: 'Matsuba',
    gender: 'female',
    birthDate: '2014-07-17',
    birthPlace: '静岡市立日本平動物園',
    personality: '少し恥ずかしがり屋だが、子供たちには優しい。',
    favoriteFood: 'タケノコ・バナナ',
    hobby: '昼寝・毛づくろい',
    photoUrl: '/pandas/matsuba.jpg',
    parentIds: [],
    childrenIds: ['niko', 'reifa'],
    partnerId: 'mocchi',
    bio: '静岡市立日本平動物園から来園。モッチーと夫婦で、双子のニーコとレイファのお母さん。',
    favoriteCount: 0,
  },
  {
    id: 'mocchi',
    name: 'モッチー',
    nameEn: 'Mocchi',
    gender: 'male',
    birthDate: '2015-06-24',
    birthPlace: '鯖江市西山動物園',
    personality: '好奇心旺盛でいつも探索している。',
    favoriteFood: 'リンゴ・ぶどう',
    hobby: '探索・遊び',
    photoUrl: '/pandas/mocchi.jpg',
    parentIds: ['kirari'],
    childrenIds: ['niko', 'reifa'],
    partnerId: 'matsuba',
    bio: 'キラリの息子として西山動物園で生まれた。まつばと夫婦で、双子のニーコとレイファのお父さん。',
    favoriteCount: 0,
  },
  {
    id: 'tiara',
    name: 'ティアラ',
    nameEn: 'Tiara',
    gender: 'female',
    birthDate: '2015-07-06',
    birthPlace: '神戸市立王子動物園',
    personality: '気品があり、優雅に動く。',
    favoriteFood: 'イチゴ・タケノコ',
    hobby: 'ゆったり散歩・木の上で休む',
    photoUrl: '/pandas/tiara.jpg',
    parentIds: ['minfa'],
    childrenIds: [],
    bio: 'ミンファの娘。神戸市立王子動物園から来園した気品あるパンダ。',
    favoriteCount: 0,
  },
  {
    id: 'kanoko',
    name: 'かのこ',
    nameEn: 'Kanoko',
    gender: 'female',
    birthDate: '2016-06-24',
    birthPlace: '多摩動物公園',
    personality: '人懐っこくて愛嬌がある。',
    favoriteFood: 'リンゴ・バンブーシュート',
    hobby: '観察・昼寝',
    photoUrl: '/pandas/kanoko.jpg',
    parentIds: [],
    childrenIds: ['kaede'],
    partnerId: 'light',
    bio: '多摩動物公園から来園。ライトと夫婦でかえでのお母さん。愛嬌たっぷりの人気者。',
    favoriteCount: 0,
  },
  {
    id: 'kanta',
    name: 'かんた',
    nameEn: 'Kanta',
    gender: 'male',
    birthDate: '2018-07-12',
    birthPlace: '秋田市大森山動物園',
    personality: '少し慎重だが、慣れると甘えん坊になる。',
    favoriteFood: 'バンブーシュート・リンゴ',
    hobby: 'ゆっくり歩き回ること',
    photoUrl: '/pandas/kanta.png',
    parentIds: [],
    childrenIds: [],
    bio: '秋田市大森山動物園から来園したオスのパンダ。慎重な性格だがとても可愛い。',
    favoriteCount: 0,
  },
  {
    id: 'niko',
    name: 'ニーコ',
    nameEn: 'Niko',
    gender: 'female',
    birthDate: '2019-07-12',
    birthPlace: '鯖江市西山動物園',
    personality: 'おっとりしていて、いつもレイファとそばにいる。',
    favoriteFood: 'タケノコ・バナナ',
    hobby: 'レイファと遊ぶこと',
    photoUrl: '/pandas/niko.jpg',
    parentIds: ['mocchi', 'matsuba'],
    childrenIds: [],
    bio: 'モッチーとまつばの娘。レイファとは双子で、西山動物園生まれのかわいい姉妹。',
    favoriteCount: 0,
  },
  {
    id: 'reifa',
    name: '令花（レイファ）',
    nameEn: 'Reifa',
    gender: 'female',
    birthDate: '2019-07-12',
    birthPlace: '鯖江市西山動物園',
    personality: '活発でいつも元気。ニーコといつも一緒にいる。',
    favoriteFood: 'リンゴ・イチゴ',
    hobby: 'ニーコと追いかけっこ',
    photoUrl: '/pandas/reifa.jpg',
    parentIds: ['mocchi', 'matsuba'],
    childrenIds: [],
    bio: 'モッチーとまつばの娘。ニーコとは双子で、元気いっぱいの西山動物園生まれ。',
    favoriteCount: 0,
  },
  {
    id: 'kaede',
    name: 'かえで',
    nameEn: 'Kaede',
    gender: 'female',
    birthDate: '2022-06-27',
    birthPlace: '鯖江市西山動物園',
    personality: '甘えん坊で、いつもお母さんのそばにいたがる。',
    favoriteFood: 'イチゴ・タケノコ',
    hobby: 'ぶら下がり・転がること',
    photoUrl: '/pandas/kaede.png',
    parentIds: ['light', 'kanoko'],
    childrenIds: [],
    bio: 'ライトとかのこの娘。2022年生まれの西山動物園の最年少。ふわふわの毛がとびきりかわいい。',
    favoriteCount: 0,
  },
]

export const KEEPER_DIARIES: KeeperDiary[] = [
  {
    id: 'diary-1',
    date: '2026-08-20',
    title: 'かえで、ぐんぐん成長中！',
    content:
      '最近のかえではどんどん活発になってきました。今日はライトのあとをちょこちょことついて歩く姿がとても愛らしく、来園された方々からも歓声が上がっていました。すくすく育ってくれて嬉しいです。',
    pandaIds: ['kaede', 'light'],
    authorName: '田中飼育員',
  },
  {
    id: 'diary-2',
    date: '2026-08-18',
    title: 'ニーコとレイファの双子タイム',
    content:
      'ニーコとレイファがいつも通りくっついて遊んでいました。双子ならではのシンクロした動きが面白く、どちらがどちらか見分けるのに飼育員も一苦労です（笑）。今日はタケノコを仲良く食べる姿が見られました。',
    pandaIds: ['niko', 'reifa'],
    authorName: '山田飼育員',
  },
  {
    id: 'diary-3',
    date: '2026-08-15',
    title: 'ミンファ、今日も元気です',
    content:
      'ベテランのミンファは今日もどっしりと木の上で日向ぼっこ。20歳を超えてもこんなに元気でいてくれるのは飼育員としてとても嬉しいです。長生きしてね！',
    pandaIds: ['minfa'],
    authorName: '田中飼育員',
  },
  {
    id: 'diary-4',
    date: '2026-08-10',
    title: 'まつばとモッチーのほのぼのタイム',
    content:
      'まつばとモッチーがご飯のあと並んで毛づくろいをしていました。夫婦仲の良さが伝わってくるシーンで、思わず写真を撮りたくなりました。こういう瞬間が飼育員冥利に尽きます。',
    pandaIds: ['matsuba', 'mocchi'],
    authorName: '山田飼育員',
  },
]

export const PANDA_BLOGS: PandaBlog[] = [
  {
    id: 'blog-kaede-1',
    pandaId: 'kaede',
    date: '2026-08-22',
    title: 'きょうもパパといっしょ！',
    content:
      'きょうはパパのライトのあとをずっとついてあるいたよ〜！パパはあしがはやくておいつくのがたいへんだったけど、すごくたのしかった。またあそぼうね！',
    mood: '🎉',
  },
  {
    id: 'blog-niko-1',
    pandaId: 'niko',
    date: '2026-08-21',
    title: 'レイファとけんかしたけど仲直り',
    content:
      'きょうはレイファとすこしもめちゃったけど、タケノコをいっしょにたべたらなかなおりしたよ。やっぱりタケノコはサイコーだね。',
    mood: '🤝',
  },
  {
    id: 'blog-reifa-1',
    pandaId: 'reifa',
    date: '2026-08-21',
    title: 'ニーコとタケノコパーティー',
    content:
      'ニーコとちょっともめたけどすぐなかなおり！タケノコをいっしょにたべたらきもちよくなった。またあしたもいっしょにあそぼうね！',
    mood: '😊',
  },
  {
    id: 'blog-kirari-1',
    pandaId: 'kirari',
    date: '2026-08-19',
    title: 'ライトとモッチーの成長が嬉しいです',
    content:
      'ライトもモッチーもすっかり立派になって、それぞれ家族を持ちました。お母さんとして誇らしいです。木の上からふたりの姿をそっと見守っています。',
    mood: '😌',
  },
  {
    id: 'blog-light-1',
    pandaId: 'light',
    date: '2026-08-20',
    title: 'かえでのお世話、がんばってます',
    content:
      'かえでがいっぱい動き回るようになってきた。うれしい反面、ちょっとくたびれることも…。でもあのかわいい顔を見るとぜんぶふっとんじゃうね！',
    mood: '💪',
  },
]
