import type { AncestorPanda } from './types'

export const ANCESTOR_PANDAS: AncestorPanda[] = [
  {
    id: 'panpan',
    name: '胖胖（パンパン）',
    nameEn: 'panpan',
    gender: 'female',
    birthDate: '1984-11-16',
    deceasedDate: '1998-09-28',
    photoUrl: '/pandas/ancestors/panpan.jpg',
    parentIds: [],
    partnerIds: ["keikei"],
    childrenIds: ["yuyu", "rinrin", "aiai"],
    isNishiyamaResident: true,
  },
  {
    id: 'shushu',
    name: '秀秀（シュウシュウ）',
    nameEn: 'shushu',
    gender: 'female',
    birthDate: '1984-11-17',
    deceasedDate: '1988-02-27',
    parentIds: [],
    partnerIds: ["keikei"],
    childrenIds: ["tantan", "reirei", "yoyo", "ranran"],
    isNishiyamaResident: true,
  },
  {
    id: 'keikei',
    name: '慶慶（ケイケイ）',
    nameEn: 'keikei',
    gender: 'male',
    birthDate: '1984-11-18',
    deceasedDate: '1990-11-24',
    parentIds: [],
    partnerIds: ["panpan", "shushu"],
    childrenIds: ["yuyu", "rinrin", "tantan", "reirei", "yoyo", "ranran", "aiai"],
    isNishiyamaResident: true,
  },
  {
    id: 'yuyu',
    name: '遊遊（ユウユウ）',
    nameEn: 'yuyu',
    gender: 'female',
    birthDate: '1986-07-05',
    deceasedDate: '2005-12-12',
    transferDate: '1987-12-16',
    transferDestination: '神戸市立王子動物園',
    photoUrl: '/pandas/ancestors/yuyu.jpg',
    parentIds: ["keikei", "panpan"],
    partnerIds: [],
    childrenIds: ["tenten", "chichi", "hana", "akane", "kaori", "kusu", "sabataro", "chunchun", "hisashi"],
    isNishiyamaResident: true,
  },
  {
    id: 'rinrin',
    name: '鈴鈴（リンリン）',
    nameEn: 'rinrin',
    gender: 'female',
    birthDate: '1986-07-05',
    deceasedDate: '2006-03-17',
    parentIds: ["keikei", "panpan"],
    partnerIds: [],
    childrenIds: ["chichi", "hisashi"],
    isNishiyamaResident: true,
  },
  {
    id: 'tantan',
    name: '誕誕（タンタン）',
    nameEn: 'tantan',
    gender: 'male',
    birthDate: '1986-07-05',
    deceasedDate: '1987-01-20',
    parentIds: ["keikei", "shushu"],
    partnerIds: [],
    childrenIds: [],
    isNishiyamaResident: true,
  },
  {
    id: 'reirei',
    name: '麗麗（レイレイ）',
    nameEn: 'reirei',
    gender: 'female',
    birthDate: '1986-07-05',
    deceasedDate: '1995-10-24',
    transferDate: '1991-12-12',
    transferDestination: '天王寺動物園',
    photoUrl: '/pandas/ancestors/reirei.jpg',
    parentIds: ["keikei", "shushu"],
    partnerIds: [],
    childrenIds: ["kusu"],
    isNishiyamaResident: true,
  },
  {
    id: 'yoyo',
    name: '陽陽（ヨウヨウ）',
    nameEn: 'yoyo',
    gender: 'male',
    birthDate: '1987-07-26',
    deceasedDate: '2007-11-26',
    transferDate: '1988-11-24',
    transferDestination: '長野市茶臼山動物園',
    parentIds: ["keikei", "shushu"],
    partnerIds: [],
    childrenIds: [],
    isNishiyamaResident: true,
  },
  {
    id: 'ranran',
    name: '蘭蘭（ランラン）',
    nameEn: 'ranran',
    gender: 'female',
    birthDate: '1987-07-26',
    deceasedDate: '2007-02-24',
    photoUrl: '/pandas/ancestors/ranran.jpg',
    parentIds: ["keikei", "shushu"],
    partnerIds: [],
    childrenIds: ["tenten", "hana", "akane", "kaori", "sabataro", "chunchun"],
    isNishiyamaResident: true,
  },
  {
    id: 'aiai',
    name: '愛愛（アイアイ）',
    nameEn: 'aiai',
    gender: 'female',
    birthDate: '1988-06-25',
    deceasedDate: '2009-01-25',
    parentIds: ["keikei", "panpan"],
    partnerIds: [],
    childrenIds: ["kozue", "ryo", "kohei", "takashi", "tsuyoshi", "tommy"],
    isNishiyamaResident: true,
  },
  {
    id: 'yuyu2',
    name: '友友（ユウユウ）',
    nameEn: 'yuyu2',
    gender: 'male',
    birthDate: '1987-05-31',
    deceasedDate: '2007-12-19',
    birthPlace: '長野市茶臼山動物園',
    transferDate: '1988-11-25',
    parentIds: ["keikei", "shushu"],  // 第2世代として設定（1987年生まれ、慶慶・秀秀の子供と推定）
    partnerIds: ["ranran", "reirei", "rinrin"],
    childrenIds: [],
    isNishiyamaResident: true,
  },
  {
    id: 'tenten',
    name: '天天（テンテン）',
    nameEn: 'tenten',
    gender: 'male',
    birthDate: '1995-06-30',
    deceasedDate: '2014-05-06',
    parentIds: ["yuyu", "ranran"],
    partnerIds: [],
    childrenIds: ["meimei", "hanahana", "maomao"],
    isNishiyamaResident: true,
  },
  {
    id: 'スイスイ',
    name: '松松（スイスイ）',
    nameEn: 'スイスイ',
    gender: 'male',
    birthDate: '1995-07-04',
    transferDate: '1996-09-19',
    transferDestination: '高知県立のいち動物公園',
    parentIds: ["yuyu2", "rinrin"],  // 第3世代として設定（1995年生まれ、友友・鈴鈴の子供と推定）
    partnerIds: [],
    childrenIds: [],
    isNishiyamaResident: true,
  },
  {
    id: 'chichi',
    name: '吉吉（チィチィ）',
    nameEn: 'chichi',
    gender: 'male',
    birthDate: '1996-06-21',
    deceasedDate: '2013-12-07',
    parentIds: ["yuyu", "rinrin"],
    partnerIds: [],
    childrenIds: [],
    isNishiyamaResident: true,
  },
  {
    id: 'hana',
    name: '花（ハナ）',
    nameEn: 'hana',
    gender: 'female',
    birthDate: '1997-06-24',
    deceasedDate: '2016-01-07',
    photoUrl: '/pandas/ancestors/hana.jpg',
    parentIds: ["yuyu", "ranran"],
    partnerIds: [],
    childrenIds: ["chacha", "renren", "koko"],
    isNishiyamaResident: true,
  },
  {
    id: 'akane',
    name: '茜（あかね）',
    nameEn: 'akane',
    gender: 'female',
    birthDate: '1998-07-07',
    deceasedDate: '2019-07-03',
    parentIds: ["yuyu", "ranran"],
    partnerIds: [],
    childrenIds: ["fafa"],
    isNishiyamaResident: true,
  },
  {
    id: 'kaori',
    name: '香（かおり）',
    nameEn: 'kaori',
    gender: 'female',
    birthDate: '1999-06-26',
    deceasedDate: '2017-11-13',
    parentIds: ["yuyu", "ranran"],
    partnerIds: [],
    childrenIds: ["kuna"],
    isNishiyamaResident: true,
  },
  {
    id: 'kozue',
    name: '梢（こずえ）',
    nameEn: 'kozue',
    gender: 'female',
    birthDate: '2000-07-13',
    deceasedDate: '2019-02-22',
    parentIds: ["aiai"],
    partnerIds: [],
    childrenIds: [],
    isNishiyamaResident: true,
  },
  {
    id: 'kusu',
    name: '楠（くす）',
    nameEn: 'kusu',
    gender: 'male',
    birthDate: '2001-07-15',
    deceasedDate: '2015-02-21',
    photoUrl: '/pandas/ancestors/kusu.jpg',
    parentIds: ["yuyu", "ranran", "reirei"],
    partnerIds: [],
    childrenIds: [],
    isNishiyamaResident: true,
  },
  {
    id: 'meimei',
    name: '明明（メイメイ）',
    nameEn: 'meimei',
    gender: 'female',
    birthDate: '2002-06-26',
    deceasedDate: '2020-09-21',
    parentIds: ["tenten", "yuyu"],
    partnerIds: [],
    childrenIds: ["sakura", "riri"],
    isNishiyamaResident: false,
  },
  {
    id: 'sabataro',
    name: 'サバタロウ',
    nameEn: 'sabataro',
    gender: 'male',
    birthDate: '2002-06-30',
    deceasedDate: '2003-03-10',
    parentIds: ["yuyu", "ranran"],
    partnerIds: [],
    childrenIds: [],
    isNishiyamaResident: true,
  },
  {
    id: 'hanahana',
    name: 'ハナハナ',
    nameEn: 'hanahana',
    gender: 'female',
    birthDate: '2003-07-13',
    deceasedDate: '2022-05-26',
    parentIds: ["tenten", "yuyu"],
    partnerIds: [],
    childrenIds: ["hikaru", "himari"],
    isNishiyamaResident: false,
  },
  {
    id: 'ryo',
    name: 'リョウ',
    nameEn: 'ryo',
    gender: 'male',
    birthDate: '2003-07-14',
    transferDate: '2004-11-20',
    transferDestination: '池田動物園',
    parentIds: ["aiai"],
    partnerIds: [],
    childrenIds: [],
    isNishiyamaResident: false,
  },
  {
    id: 'maomao',
    name: 'マオマオ',
    nameEn: 'maomao',
    gender: 'male',
    birthDate: '2004-07-04',
    deceasedDate: '2019-11-28',
    parentIds: ["tenten", "yuyu"],
    partnerIds: [],
    childrenIds: ["kirara", "niko_ancestor", "karin"],
    isNishiyamaResident: false,
  },
  {
    id: 'kohei',
    name: 'コウヘイ',
    nameEn: 'kohei',
    gender: 'male',
    birthDate: '2005-07-15',
    deceasedDate: '2023-01-12',
    parentIds: ["aiai"],
    partnerIds: [],
    childrenIds: [],
    isNishiyamaResident: true,
  },
  {
    id: 'chunchun',
    name: 'チュンチュン',
    nameEn: 'chunchun',
    gender: 'female',
    birthDate: '2005-07-15',
    deceasedDate: '2023-06-01',
    parentIds: ["yuyu", "ranran"],
    partnerIds: [],
    childrenIds: [],
    isNishiyamaResident: false,
  },
  {
    id: 'chacha',
    name: 'チャチャ',
    nameEn: 'chacha',
    gender: 'female',
    birthDate: '1997-06-17',  // 飼育個体情報ファイルより
    deceasedDate: '2012-04-07',  // 飼育個体情報ファイルより
    photoUrl: '/pandas/ancestors/chacha.jpg',
    parentIds: ["takashi", "shunshun"],  // 飼育個体情報ファイルより（タカシ、純純）
    partnerIds: ["takashi"],
    childrenIds: ["lara", "chata"],  // 飼育個体情報ファイルより
    isNishiyamaResident: true,
  },
  {
    id: 'renren',
    name: 'レンレン',
    nameEn: 'renren',
    gender: 'male',
    birthDate: '2007-07-04',
    deceasedDate: '2019-04-05',
    parentIds: ["hana"],
    partnerIds: [],
    childrenIds: ["homare", "tomoe", "musashi", "benkei"],
    isNishiyamaResident: false,
  },
  {
    id: 'takashi',
    name: 'タカシ',
    nameEn: 'takashi',
    gender: 'male',
    birthDate: '2007-07-14',
    transferDate: '2008-12-18',
    transferDestination: '池田動物園',
    photoUrl: '/pandas/ancestors/takashi.jpg',
    parentIds: ["aiai"],
    partnerIds: [],
    childrenIds: [],
    isNishiyamaResident: true,
  },
  {
    id: 'koko',
    name: 'コウコウ',
    nameEn: 'koko',
    gender: 'male',
    birthDate: '2008-07-14',
    deceasedDate: '2024-10-30',
    parentIds: ["hana"],
    partnerIds: [],
    childrenIds: ["futa"],
    isNishiyamaResident: false,
  },
  {
    id: 'fafa',
    name: 'ファファ',
    nameEn: 'fafa',
    gender: 'female',
    birthDate: '2009-07-05',
    deceasedDate: '2024-07-25',
    photoUrl: '/pandas/ancestors/fafa.jpg',
    parentIds: ["akane"],
    partnerIds: [],
    childrenIds: ["shinobu"],
    isNishiyamaResident: true,
  },
  {
    id: 'tsuyoshi',
    name: 'ツヨシ',
    nameEn: 'tsuyoshi',
    gender: 'male',
    birthDate: '2009-07-14',
    transferDate: '2011-03-11',
    transferDestination: '宇都宮動物園',
    parentIds: ["aiai"],
    partnerIds: [],
    childrenIds: [],
    isNishiyamaResident: true,
  },
  {
    id: 'kuna',
    name: 'クーナ',
    nameEn: 'kuna',
    gender: 'female',
    birthDate: '2010-07-06',
    deceasedDate: '2024-11-01',
    parentIds: ["kaori"],
    partnerIds: [],
    childrenIds: ["haruka"],
    isNishiyamaResident: false,
  },
  {
    id: 'sakura',
    name: 'サクラ',
    nameEn: 'sakura',
    gender: 'female',
    birthDate: '2010-07-15',
    deceasedDate: '2024-04-17',
    photoUrl: '/pandas/ancestors/sakura.jpg',
    parentIds: ["meimei", "riki"],  // 両親を追加：meimei(メス) + riki(オス、第3世代)
    partnerIds: ["lili"],
    childrenIds: ["kotaro", "matsuba", "kirari"],
    isNishiyamaResident: false,
  },
  {
    id: 'hisashi',
    name: 'ヒサシ',
    nameEn: 'hisashi',
    gender: 'male',
    birthDate: '2010-07-15',
    deceasedDate: '2024-09-29',
    photoUrl: '/pandas/ancestors/hisashi.jpg',
    parentIds: ["yuyu", "rinrin"],
    partnerIds: [],
    childrenIds: [],
    isNishiyamaResident: true,
  },
  {
    id: 'tommy',
    name: 'トミー',
    nameEn: 'tommy',
    gender: 'male',
    birthDate: '2010-07-15',
    transferDate: '2011-03-29',
    transferDestination: '宇都宮動物園',
    parentIds: ["aiai"],
    partnerIds: [],
    childrenIds: [],
    isNishiyamaResident: true,
  },
  {
    id: 'riri',
    name: 'リーリー',
    nameEn: 'riri',
    gender: 'female',
    birthDate: '2011-07-15',
    deceasedDate: '2024-02-01',
    parentIds: ["meimei"],
    partnerIds: [],
    childrenIds: ["yuki", "sora"],
    isNishiyamaResident: false,
  },
  {
    id: 'hikaru',
    name: 'ヒカル',
    nameEn: 'hikaru',
    gender: 'male',
    birthDate: '2012-06-26',
    transferDate: '2014-03-10',
    transferDestination: '神戸市立王子動物園',
    parentIds: ["hanahana"],
    partnerIds: [],
    childrenIds: [],
    isNishiyamaResident: false,
  },
  {
    id: 'himari',
    name: 'ヒマリ',
    nameEn: 'himari',
    gender: 'female',
    birthDate: '2012-06-26',
    transferDate: '2014-03-10',
    transferDestination: '神戸市立王子動物園',
    parentIds: ["hanahana"],
    partnerIds: [],
    childrenIds: [],
    isNishiyamaResident: false,
  },
  {
    id: 'kirara',
    name: 'キララ',
    nameEn: 'kirara',
    gender: 'female',
    birthDate: '2013-06-26',
    deceasedDate: '2023-09-28',
    photoUrl: '/pandas/ancestors/kirara.jpg',
    parentIds: ["maomao"],
    partnerIds: [],
    childrenIds: [],
    isNishiyamaResident: true,
  },
  {
    id: 'niko_ancestor',
    name: 'ニコ',
    nameEn: 'niko',
    gender: 'female',
    birthDate: '2013-06-26',
    deceasedDate: '2024-05-08',
    parentIds: ["maomao"],
    partnerIds: [],
    childrenIds: [],
    isNishiyamaResident: false,
  },
  {
    id: 'hikari',
    name: 'ヒカリ',
    nameEn: 'hikari',
    gender: 'female',
    birthDate: '2014-07-04',
    deceasedDate: '2024-04-09',
    photoUrl: '/pandas/ancestors/hikari.jpg',
    parentIds: ["chacha"],
    partnerIds: [],
    childrenIds: [],
    isNishiyamaResident: false,
  },
  {
    id: 'kirin',
    name: 'キリン',
    nameEn: 'kirin',
    gender: 'male',
    birthDate: '2014-07-04',
    deceasedDate: '2024-04-27',
    parentIds: ["chacha"],
    partnerIds: [],
    childrenIds: [],
    isNishiyamaResident: false,
  },
  {
    id: 'homare',
    name: 'ホマレ',
    nameEn: 'homare',
    gender: 'male',
    birthDate: '2014-07-15',
    deceasedDate: '2023-12-24',
    parentIds: ["renren"],
    partnerIds: [],
    childrenIds: [],
    isNishiyamaResident: false,
  },
  {
    id: 'karin',
    name: 'カリン',
    nameEn: 'karin',
    gender: 'female',
    birthDate: '2014-07-15',
    transferDate: '2015-11-12',
    transferDestination: '池田動物園',
    parentIds: ["maomao"],
    partnerIds: [],
    childrenIds: [],
    isNishiyamaResident: false,
  },
  {
    id: 'tomoe',
    name: 'トモエ',
    nameEn: 'tomoe',
    gender: 'female',
    birthDate: '2015-07-01',
    deceasedDate: '2024-02-05',
    parentIds: ["renren"],
    partnerIds: [],
    childrenIds: [],
    isNishiyamaResident: false,
  },
  {
    id: 'musashi',
    name: 'ムサシ',
    nameEn: 'musashi',
    gender: 'male',
    birthDate: '2016-07-13',
    transferDate: '2017-11-16',
    transferDestination: '八木山動物公園フジサキの杜',
    parentIds: ["renren"],
    partnerIds: [],
    childrenIds: [],
    isNishiyamaResident: false,
  },
  {
    id: 'benkei',
    name: 'ベンケイ',
    nameEn: 'benkei',
    gender: 'male',
    birthDate: '2016-07-13',
    transferDate: '2017-11-16',
    transferDestination: '秋田市大森山動物園',
    parentIds: ["renren"],
    partnerIds: [],
    childrenIds: [],
    isNishiyamaResident: false,
  },
  {
    id: 'futa',
    name: 'フウタ',
    nameEn: 'futa',
    gender: 'male',
    birthDate: '2017-07-15',
    transferDate: '2018-11-20',
    transferDestination: '札幌市円山動物園',
    parentIds: ["koko"],
    partnerIds: [],
    childrenIds: [],
    isNishiyamaResident: false,
  },
  {
    id: 'shinobu',
    name: 'シノブ',
    nameEn: 'shinobu',
    gender: 'female',
    birthDate: '2018-07-06',
    transferDate: '2019-11-19',
    transferDestination: '姫路市立動物園',
    parentIds: ["fafa"],
    partnerIds: [],
    childrenIds: [],
    isNishiyamaResident: false,
  },
  {
    id: 'haruka',
    name: 'ハルカ',
    nameEn: 'haruka',
    gender: 'female',
    birthDate: '2019-07-13',
    transferDate: '2020-11-24',
    transferDestination: '日立市かみね動物園',
    parentIds: ["kuna"],
    partnerIds: [],
    childrenIds: [],
    isNishiyamaResident: false,
  },
  {
    id: 'kotaro',
    name: 'コタロウ',
    nameEn: 'kotaro',
    gender: 'male',
    birthDate: '2019-07-15',
    transferDate: '2020-11-24',
    transferDestination: '姫路市立動物園',
    parentIds: ["sakura"],
    partnerIds: [],
    childrenIds: [],
    isNishiyamaResident: false,
  },
  {
    id: 'yuki',
    name: 'ユキ',
    nameEn: 'yuki',
    gender: 'male',
    birthDate: '2020-07-11',
    transferDate: '2021-11-16',
    transferDestination: '日立市かみね動物園',
    parentIds: ["riri"],
    partnerIds: [],
    childrenIds: [],
    isNishiyamaResident: false,
  },
  {
    id: 'sora',
    name: 'ソラ',
    nameEn: 'sora',
    gender: 'female',
    birthDate: '2020-07-11',
    transferDate: '2021-11-16',
    transferDestination: '姫路市立動物園',
    parentIds: ["riri"],
    partnerIds: [],
    childrenIds: [],
    isNishiyamaResident: false,
  },
  // === 23 MISSING HISTORICAL PANDAS ===
  {
    id: 'meimei2',
    name: '美美（メイメイ）',
    gender: 'female',
    birthDate: '1989-06-19',
    deceasedDate: '2007-11-10',
    transferDate: '2001-11-09',
    transferDestination: '江戸川区自然動物園',
    birthPlace: '仙台市八木山動物公園',
    parentIds: ["keikei", "panpan"],  // 第2世代として設定（1989年生まれ、慶慶・胖胖の子供と推定）
    partnerIds: ["pinpin"],
    childrenIds: ["yanyan1", "saisai"],
    isNishiyamaResident: true,
  },
  {
    id: 'pinpin',
    name: '平平（ピンピン）',
    gender: 'female',
    birthDate: '1989-06-28',
    deceasedDate: '2008-01-05',
    birthPlace: '周南市徳山動物園',
    parentIds: ["keikei", "shushu"],  // 第2世代として設定（1989年生まれ、慶慶・秀秀の子供と推定）
    partnerIds: ["aiai", "meimei2"],
    childrenIds: ["kozue", "yanyan1", "saisai", "ryo", "kouhei", "takashi", "tsuyoshi", "tommy"],
    isNishiyamaResident: true,
  },
  {
    id: 'yanyan1',
    name: '陽陽（ヤンヤン）',
    gender: 'female',
    birthDate: '1992-06-19',
    deceasedDate: '2010-07-04',
    transferDate: '1993-04-22',
    transferDestination: '旭川市旭山動物園',
    photoUrl: '/pandas/ancestors/ヤンヤン.jpg',
    parentIds: ["pinpin", "meimei2"],
    partnerIds: [],
    childrenIds: [],
    isNishiyamaResident: true,
  },
  {
    id: 'saisai',
    name: 'サイサイ',
    gender: 'female',
    birthDate: '1992-06-19',
    deceasedDate: '2006-07-01',
    transferDate: '1994-04-21',
    transferDestination: '姫路市立動物園',
    parentIds: ["pinpin", "meimei2"],
    partnerIds: [],
    childrenIds: [],
    isNishiyamaResident: true,
  },
  {
    id: 'marimo',
    name: 'マリモ',
    gender: 'female',
    birthDate: '1995-07-05',
    deceasedDate: '2008-02-22',
    transferDate: '2007-12-03',
    transferDestination: '姫路市立動物園',
    birthPlace: '釧路市動物園',
    photoUrl: '/pandas/ancestors/マリモ.jpg',
    parentIds: ["yuyu2", "ranran"],  // 第3世代として設定（1995年生まれ、友友・蘭蘭の子供と推定）
    partnerIds: ["koukou"],
    childrenIds: [],
    isNishiyamaResident: true,
  },
  {
    id: 'kousei',
    name: 'コウセイ',
    gender: 'female',
    birthDate: '2000-06-27',
    deceasedDate: '2018-04-03',
    transferDate: '2003-12-26',
    transferDestination: '横浜市立よこはま動物園',
    parentIds: ["takashi", "chacha"],
    partnerIds: [],
    childrenIds: [],
    isNishiyamaResident: true,
  },
  {
    id: 'chata',
    name: 'チャタ',
    gender: 'female',
    birthDate: '2002-06-25',
    deceasedDate: '2014-12-18',
    photoUrl: '/pandas/ancestors/チャタ.jpg',
    parentIds: ["takashi", "chacha"],
    partnerIds: ["minfa"],
    childrenIds: ["fafa", "minmin", "charmin", "sousou", "milky"],
    isNishiyamaResident: true,
  },
  {
    id: 'shunshun',
    name: '純純（シュンシュン）',
    gender: 'female',
    birthDate: '2001-06-28',
    deceasedDate: '2016-12-30',
    transferDate: '2012/1～4まで多摩',
    transferDestination: '東京都多摩動物公園',
    birthPlace: 'ひらかたパーク',
    photoUrl: '/pandas/ancestors/シュンシュン.jpg',
    parentIds: ["tenten", "yanyan1"],  // 第4世代として設定（2001年生まれ、天天・陽陽の子供と推定）
    partnerIds: ["chacha", "lara"],
    childrenIds: ["chao", "shurara", "rairai", "yanyan2", "shinshin"],
    isNishiyamaResident: true,
  },
  {
    id: 'chao',
    name: 'チャオ',
    gender: 'female',
    birthDate: '2006-07-06',
    deceasedDate: '2023-02-18',
    transferDate: '2009-01-23',
    transferDestination: '長野市茶臼山動物園',
    photoUrl: '/pandas/ancestors/チャオ.jpg',
    parentIds: ["shunshun", "chacha"],
    partnerIds: [],
    childrenIds: [],
    isNishiyamaResident: true,
  },
  {
    id: 'shurara',
    name: 'シュララ',
    gender: 'female',
    birthDate: '2007-06-23',
    deceasedDate: '2016-10-01',
    transferDate: '2010-12-22',
    transferDestination: '仙台市八木山動物公園',
    photoUrl: '/pandas/ancestors/シュララ.jpg',
    parentIds: ["shunshun", "lara"],
    partnerIds: [],
    childrenIds: [],
    isNishiyamaResident: true,
  },
  {
    id: 'rairai',
    name: '来来（ライライ）',
    gender: 'female',
    birthDate: '2008-07-01',
    deceasedDate: '2022-02-04',
    transferDate: '2011-06-02',
    transferDestination: '東武動物公園',
    photoUrl: '/pandas/ancestors/ライライ.jpg',
    parentIds: ["shunshun", "chacha"],
    partnerIds: [],
    childrenIds: [],
    isNishiyamaResident: true,
  },
  {
    id: 'yanyan2',
    name: 'ヤンヤン',
    gender: 'female',
    birthDate: '2010-06-24',
    deceasedDate: '2021-01-23',
    parentIds: ["shunshun", "lara"],
    partnerIds: ["kirari"],
    childrenIds: ["light", "hikari2", "mocchi", "sakuya", "meishan"],
    isNishiyamaResident: true,
  },
  {
    id: 'shinshin',
    name: 'シンシン',
    gender: 'female',
    birthDate: '2010-06-24',
    deceasedDate: '2024-01-24',
    transferDate: '2013-02-28',
    transferDestination: 'アドベンチャーワールド',
    photoUrl: '/pandas/ancestors/シンシン.jpg',
    parentIds: ["shunshun", "lara"],
    partnerIds: [],
    childrenIds: [],
    isNishiyamaResident: true,
  },
  {
    id: 'minmin',
    name: 'ミンミン',
    gender: 'female',
    birthDate: '2010-06-28',
    deceasedDate: '2024-04-10',
    transferDate: '2012-04-23',
    transferDestination: 'とくしま動物園',
    photoUrl: '/pandas/ancestors/ミンミン.jpg',
    parentIds: ["chata", "minfa"],
    partnerIds: [],
    childrenIds: [],
    isNishiyamaResident: true,
  },
  {
    id: 'charmin',
    name: 'チャーミン',
    gender: 'female',
    birthDate: '2011-07-16',
    deceasedDate: '2021-08-22',
    transferDate: '2014-02-03',
    transferDestination: '旭川市旭山動物園',
    photoUrl: '/pandas/ancestors/チャーミン.jpg',
    parentIds: ["chata", "minfa"],
    partnerIds: [],
    childrenIds: [],
    isNishiyamaResident: true,
  },
  {
    id: 'sousou',
    name: 'ソウソウ',
    gender: 'female',
    birthDate: '2012-07-08',
    deceasedDate: '2020-12-01',
    transferDate: '2015-03-02',
    transferDestination: '埼玉県こども動物自然公園',
    photoUrl: '/pandas/ancestors/ソウソウ.jpg',
    parentIds: ["chata", "minfa"],
    partnerIds: [],
    childrenIds: [],
    isNishiyamaResident: true,
  },
  {
    id: 'kirari',
    name: 'キラリ',
    gender: 'female',
    birthDate: '2011-06-27',
    deceasedDate: '2025-07-06',
    birthPlace: '姫路セントラルパーク',
    parentIds: ["sakura", "lili"],  // 第6世代として設定（2011年生まれ、サクラ・リーリーの子供と推定）
    partnerIds: ["yanyan2"],
    childrenIds: ["light", "hikari2", "mocchi", "sakuya", "meishan"],
    isNishiyamaResident: true,
  },
  {
    id: 'milky',
    name: 'ミルキー',
    gender: 'female',
    birthDate: '2013-07-07',
    deceasedDate: '2026-03-21',
    transferDate: '2020-02-26',
    transferDestination: 'アドベンチャーワールド',
    photoUrl: '/pandas/ancestors/ミルキー.jpg',
    partnerIds: ["taiyo"],
    parentIds: ["chata", "minfa"],
    childrenIds: [],
    isNishiyamaResident: true,
  },
  {
    id: 'light',
    name: 'ライト',
    gender: 'female',
    birthDate: '2013-07-18',
    parentIds: ["yanyan2", "kirari"],
    partnerIds: [],
    childrenIds: ["kaito", "kaede"],
    isNishiyamaResident: true,
  },
  {
    id: 'hikari2',
    name: 'ひかり',
    gender: 'female',
    birthDate: '2013-07-18',
    deceasedDate: '2024-03-10',
    photoUrl: '/pandas/ancestors/ひかり.jpg',
    parentIds: ["yanyan2", "kirari"],
    partnerIds: ["taiyo"],
    childrenIds: [],
    isNishiyamaResident: true,
  },
  {
    id: 'sakuya',
    name: '咲弥（さくや）',
    nameEn: 'Sakuya',
    gender: 'female',
    birthDate: '2015-06-24',
    transferDate: '2017-11-20',
    transferDestination: '天王寺動物園',
    photoUrl: '/pandas/ancestors/さくや.jpg',
    parentIds: ["yanyan2", "kirari"],
    partnerIds: [],
    childrenIds: [],
    isNishiyamaResident: true,
  },
  {
    id: 'taiyo',
    name: 'たいよう',
    gender: 'male',
    birthDate: '2013-06-15',
    birthPlace: '池田動物園',
    parentIds: ["himari", "hikaru"],  // 第6世代として設定（2013年生まれ、ヒマリ・ヒカルの子供と推定）
    partnerIds: ["hikari2", "milky", "kanoko"],
    childrenIds: ["peaceke"],
    isNishiyamaResident: true,
  },
  {
    id: 'mutan',
    name: 'ムータン',
    gender: 'female',
    birthDate: '2014-06-19',
    deceasedDate: '2024-01-31',
    transferDate: '2021-01-18',
    transferDestination: '長野市茶臼山動物園',
    birthPlace: '京都市動物園',
    photoUrl: '/pandas/ancestors/ムータン.jpg',
    parentIds: ["kirin", "homare"],  // 第6世代として設定（2014年生まれ、キリン・ホマレの子供と推定）
    partnerIds: ["tiara"],
    childrenIds: [],
    isNishiyamaResident: true,
  },
  // === pandaData.tsにのみ存在する現在の個体（親情報を追加） ===
  {
    id: 'mocchi',
    name: 'モッチー',
    gender: 'male',
    birthDate: '2015-06-24',
    birthPlace: '鯖江市西山動物園',
    parentIds: ["yanyan2", "kirari"],  // bio: キラリの息子
    partnerIds: ["matsuba"],
    childrenIds: ["niko", "reifa"],
    isNishiyamaResident: true,
  },
  {
    id: 'matsuba',
    name: 'まつば',
    gender: 'female',
    birthDate: '2014-07-17',
    birthPlace: '静岡市立日本平動物園',
    parentIds: ["sakura", "lili"],  // 第6世代と推定（2014年生まれ）
    partnerIds: ["mocchi"],
    childrenIds: ["niko", "reifa"],
    isNishiyamaResident: true,
  },
  {
    id: 'kanoko',
    name: 'かのこ',
    gender: 'female',
    birthDate: '2016-06-24',
    birthPlace: '多摩動物公園',
    parentIds: ["himari", "nico"],  // 第6世代と推定（2016年生まれ）
    partnerIds: ["light"],
    childrenIds: ["kaede"],
    isNishiyamaResident: true,
  },
  {
    id: 'kanta',
    name: 'かんた',
    gender: 'male',
    birthDate: '2018-07-12',
    birthPlace: '秋田市大森山動物園',
    parentIds: ["kirara", "kirin"],  // 第6世代と推定（2018年生まれ）
    partnerIds: ["akebi"],
    childrenIds: [],
    isNishiyamaResident: true,
  },
  {
    id: 'akebi',
    name: 'アケビ',
    gender: 'female',
    birthDate: '2020-06-29',
    birthPlace: '八木山動物公園フジサキの杜',
    parentIds: ["homare", "karin"],  // 第6世代と推定（2020年生まれ）
    partnerIds: ["kanta"],
    childrenIds: [],
    isNishiyamaResident: true,
  },
  {
    id: 'kaede',
    name: 'かえで',
    gender: 'female',
    birthDate: '2022-06-27',
    birthPlace: '鯖江市西山動物園',
    transferDate: '2025-03-03',
    transferDestination: 'いしかわ動物園',
    parentIds: ["light", "kanoko"],  // ライトとかのこの娘
    partnerIds: [],
    childrenIds: [],
    isNishiyamaResident: true,
  },
  {
    id: 'tiara',
    name: 'ティアラ',
    gender: 'female',
    birthDate: '2015-07-06',
    birthPlace: '神戸市立王子動物園',
    transferDate: '2016-03-16',
    transferDestination: '神戸市立王子動物園',
    parentIds: ["chata", "minfa"],  // ミンファの娘（pandaData.tsのbio参照）
    partnerIds: ["mutan"],
    childrenIds: [],
    isNishiyamaResident: true,
  },
  // === 不足していた個体（親チェーン補完のため追加） ===
  {
    id: 'riki',
    name: 'リキ',
    gender: 'male',
    birthDate: '1995-06-15',  // 推定：第4世代
    parentIds: ["tenten", "yanyan1"],  // 第4世代（tentenとyanyan1の子）
    partnerIds: ["meimei"],
    childrenIds: ["sakura"],
    isNishiyamaResident: false,
  },
  {
    id: 'lili',
    name: 'リーリー',
    gender: 'male',
    birthDate: '2008-06-15',  // 推定：まつば（2014年生）・キラリの親なので2008年頃と推定
    parentIds: [],  // 公式データに記載なし（飼育個体情報ファイル・家系図ファイルに未記載）
    partnerIds: ["sakura"],
    childrenIds: ["matsuba", "kirari"],
    isNishiyamaResident: false,
    // 注: 西山動物園の公式資料にliliの記載がないため、まつば・キラリの親情報から逆算して追加
    // 世代計算上、parentIdsを空にして第1世代扱いとする
  },
  {
    id: 'lara',
    name: 'ララ',
    gender: 'female',
    birthDate: '2000-06-27',  // 飼育個体情報ファイルより
    deceasedDate: '2015-02-15',
    parentIds: ["takashi", "chacha"],  // 飼育個体情報ファイルより
    partnerIds: ["shunshun"],
    childrenIds: ["yanyan2", "kirara", "shurara"],  // 飼育個体情報ファイルより
    isNishiyamaResident: true,
  },
  {
    id: 'chunchun',
    name: '春春（チュンチュン）',
    nameEn: 'Chunchun',
    gender: 'male',
    birthDate: '1992-06-22',
    deceasedDate: '2010-09-18',
    transferDate: '1994-02-22',
    transferDestination: '池田動物園',
    parentIds: [],
    partnerIds: [],
    childrenIds: [],
    isNishiyamaResident: true,
  },
  {
    id: 'ryo',
    name: '涼（リョウ）',
    nameEn: 'Ryo',
    gender: 'male',
    birthDate: '1992-07-13',
    deceasedDate: '2013-02-13',
    transferDate: '1996-03-26',
    transferDestination: '三島市立公園楽寿園',
    parentIds: [],
    partnerIds: [],
    childrenIds: [],
    isNishiyamaResident: true,
  },
  {
    id: 'kouko',
    name: '好好（コウコウ）',
    nameEn: 'Kouko',
    gender: 'male',
    birthDate: '1988-06-22',
    deceasedDate: '2008-01-05',
    parentIds: [],
    partnerIds: [],
    childrenIds: [],
    isNishiyamaResident: true,
  },
  {
    id: 'meishan',
    name: '梅香（めいしゃん）',
    nameEn: 'Meishan',
    gender: 'female',
    birthDate: '2017-06-29',
    transferDate: '2020-01-17',
    transferDestination: '伊豆シャボテン動物公園',
    photoUrl: '/pandas/ancestors/めいしゃん.jpg',
    parentIds: ["yanyan2", "kirari"],
    partnerIds: [],
    childrenIds: [],
    isNishiyamaResident: true,
  },
  {
    id: 'reifa2',
    name: 'レイファ（令花）',
    nameEn: 'Reifa',
    gender: 'female',
    birthDate: '2019-07-12',
    transferDate: '2025-04-14',
    transferDestination: '秋田市大森山動物園',
    photoUrl: '/pandas/reifa.jpg',
    parentIds: ["mocchi", "matsuba"],
    partnerIds: [],
    childrenIds: [],
    isNishiyamaResident: true,
  },
  {
    id: 'peaceke',
    name: 'ピースケ',
    nameEn: 'Peaceke',
    gender: 'male',
    birthDate: '2020-06-27',
    transferDate: '2022-01-10',
    transferDestination: '東京都立大島公園',
    photoUrl: '/pandas/ancestors/ピースケ.jpg',
    parentIds: ["taiyo", "kanoko"],
    partnerIds: [],
    childrenIds: [],
    isNishiyamaResident: true,
  },
  {
    id: 'kaito',
    name: 'カイト',
    nameEn: 'Kaito',
    gender: 'male',
    birthDate: '2022-06-27',
    transferDate: '2024-06-03',
    transferDestination: '東京都多摩動物公園',
    photoUrl: '/pandas/ancestors/カイト.jpg',
    parentIds: ["light", "kanoko"],
    partnerIds: [],
    childrenIds: [],
    isNishiyamaResident: true,
  },
]
