// 歴代パンダの名前と写真ファイル名のマッピング
export const HISTORICAL_PANDA_PHOTO_MAP: Record<string, string> = {
  // ancestors ディレクトリの写真
  '陽陽（ヤンヤン）': '/pandas/ancestors/ヤンヤン.jpg',
  'マリモ': '/pandas/ancestors/マリモ.jpg',
  'ララ': '/pandas/ancestors/ララ.jpg',
  'チャタ': '/pandas/ancestors/チャタ.jpg',
  'キララ': '/pandas/ancestors/kirara.jpg',
  '純純（シュンシュン）': '/pandas/ancestors/シュンシュン.jpg',
  'チャオ': '/pandas/ancestors/チャオ.jpg',
  'シュララ': '/pandas/ancestors/シュララ.jpg',
  '来来（ライライ）': '/pandas/ancestors/ライライ.jpg',
  'ヤンヤン': '/pandas/ancestors/ヤンヤン.jpg',
  'クス': '/pandas/ancestors/kusu.jpg',
  '遥遥（ヤオヤオ）': '/pandas/ancestors/ヤンヤン.jpg',
  '新新（シンシン）': '/pandas/ancestors/シンシン.jpg',
  'シンシン': '/pandas/ancestors/シンシン.jpg',
  '珉珉（ミンミン）': '/pandas/ancestors/ミンミン.jpg',
  'ミンミン': '/pandas/ancestors/ミンミン.jpg',
  'ソウソウ': '/pandas/ancestors/ソウソウ.jpg',
  'ひかり': '/pandas/ancestors/ひかり.jpg',
  '妃香里（ひかり）': '/pandas/ancestors/hikari.jpg',
  'カイト': '/pandas/ancestors/カイト.jpg',
  'さくや': '/pandas/ancestors/さくや.jpg',
  '咲弥（さくや）': '/pandas/ancestors/sakura.jpg',
  'めいしゃん': '/pandas/ancestors/めいしゃん.jpg',
  '明星（めいしゃん）': '/pandas/ancestors/めいしゃん.jpg',
  '梅香（めいしゃん）': '/pandas/ancestors/めいしゃん.jpg',
  'ミルキー': '/pandas/ancestors/ミルキー.jpg',
  'ムータン': '/pandas/ancestors/ムータン.jpg',
  'ピースケ': '/pandas/ancestors/ピースケ.jpg',
  'チャーミン': '/pandas/ancestors/チャーミン.jpg',
  '嬌嬌（チャウチャウ）': '/pandas/ancestors/チャオ.jpg',
  '花花（ファーファ）': '/pandas/ancestors/fafa.jpg',
  '華華（ファーファ）': '/pandas/ancestors/fafa.jpg',
  'ファファ': '/pandas/ancestors/fafa.jpg',
  '遊遊（ユウユウ）': '/pandas/ancestors/yuyu.jpg',
  '麗麗（レイレイ）': '/pandas/ancestors/reirei.jpg',
  '蘭蘭（ランラン）': '/pandas/ancestors/ranran.jpg',
  'ひさし': '/pandas/ancestors/hisashi.jpg',
  '寿（ひさし）': '/pandas/ancestors/hisashi.jpg',
  'ヒサシ': '/pandas/ancestors/hisashi.jpg',
  'たかし': '/pandas/ancestors/takashi.jpg',
  '貴志（たかし）': '/pandas/ancestors/takashi.jpg',
  'タカシ': '/pandas/ancestors/takashi.jpg',
  '華（はな）': '/pandas/ancestors/hana.jpg',
  'はな': '/pandas/ancestors/hana.jpg',
  '花（ハナ）': '/pandas/ancestors/hana.jpg',
  '楠（くす）': '/pandas/ancestors/kusu.jpg',
  '茶茶（チャチャ）': '/pandas/ancestors/chacha.jpg',
  'チャチャ': '/pandas/ancestors/chacha.jpg',
  '胖胖（パンパン）': '/pandas/ancestors/panpan.jpg',

  // pandasディレクトリの写真（歴代個体）
  'ミンファ': '/pandas/minfa.jpg',
  'キラリ': '/pandas/kirari.jpg',
  'ニーコ': '/pandas/niko.jpg',
  'レイファ（令花）': '/pandas/reifa.jpg',
  'かえで': '/pandas/kaede.png',
}

export function getHistoricalPandaPhoto(pandaName: string): string | null {
  return HISTORICAL_PANDA_PHOTO_MAP[pandaName] || null
}
