import type { SpawnPoint, SpawnPointGroup } from './types'

export const SPAWN_POINTS: SpawnPoint[] = [
  {
    id: 'zoo-entrance',
    facilityName: '西山動物園（入口）',
    coords: { lat: 35.950668, lng: 136.180943 },
    radiusMeters: 60,
    checkinMethod: 'gps',
    mascotMood: 'guide',
    rarity: 'common',
    linkedPandaId: undefined,
    note: '入口付近',
  },
  {
    id: 'zoo-panda-house',
    facilityName: '西山動物園（レッサーパンダ舎）',
    coords: { lat: 35.950668, lng: 136.180943 },
    radiusMeters: 50,
    checkinMethod: 'qr_gps',
    mascotMood: 'excited',
    rarity: 'common',
    note: 'レッサーパンダ舎付近。入口と同施設で分散配置',
  },
  {
    id: 'roadside-station',
    facilityName: '道の駅西山公園',
    coords: { lat: 35.948765, lng: 136.180423 },
    radiusMeters: 70,
    checkinMethod: 'gps',
    mascotMood: 'welcome',
    rarity: 'common',
    note: 'スタート地点・アクセス拠点',
  },
  {
    id: 'lawn-plaza-a',
    facilityName: '芝生広場（お祭り広場）A',
    coords: { lat: 35.950563, lng: 136.182293 },
    radiusMeters: 120,
    checkinMethod: 'gps',
    mascotMood: 'happy',
    rarity: 'common',
    note: '広いエリア。2点に分散のうちA地点',
  },
  {
    id: 'lawn-plaza-b',
    facilityName: '芝生広場（お祭り広場）B',
    coords: { lat: 35.950763, lng: 136.182593 },
    radiusMeters: 120,
    checkinMethod: 'gps',
    mascotMood: 'happy',
    rarity: 'common',
    note: '広いエリア。2点に分散のうちB地点（暫定座標）',
  },
  {
    id: 'musubi-hiroba',
    facilityName: '結びの広場（結びのチャイム）',
    coords: { lat: 35.949902, lng: 136.181123 },
    radiusMeters: 60,
    checkinMethod: 'gps',
    mascotMood: 'guide',
    rarity: 'common',
  },
  {
    id: 'fountain',
    facilityName: '大噴水',
    coords: { lat: 35.950114, lng: 136.181969 },
    radiusMeters: 40,
    checkinMethod: 'gps',
    mascotMood: 'excited',
    rarity: 'rare',
    rarityCondition: {
      type: 'time_range',
      startHour: 18,
      endHour: 20,
      label: '18:00〜20:00（ライトアップ時間帯）',
    },
    note: 'レアキャラはライトアップ時間帯限定',
  },
  {
    id: 'nishiyama-bridge',
    facilityName: '西山橋',
    coords: null,
    radiusMeters: 40,
    checkinMethod: 'qr_gps',
    mascotMood: 'guide',
    rarity: 'common',
    note: '座標未確定。鯖江市公園緑地課へ問い合わせ予定（0778-53-2239）',
  },
  {
    id: 'upper-garden',
    facilityName: '上段の庭',
    coords: { lat: 35.951012, lng: 136.184641 },
    radiusMeters: 65,
    checkinMethod: 'gps',
    mascotMood: 'guide',
    rarity: 'common',
    note: '嚮陽庭園エリア。現地で正確な位置を確認推奨',
  },
  {
    id: 'north-garden',
    facilityName: '北の庭',
    coords: { lat: 35.951727, lng: 136.184231 },
    radiusMeters: 65,
    checkinMethod: 'gps',
    mascotMood: 'guide',
    rarity: 'common',
  },
  {
    id: 'panda-land-a',
    facilityName: '冒険の森「パンダらんど」A',
    coords: { lat: 35.952229, lng: 136.182753 },
    radiusMeters: 100,
    checkinMethod: 'gps',
    mascotMood: 'excited',
    rarity: 'common',
    note: '敷地が広いので2点に分散のうちA地点',
  },
  {
    id: 'panda-land-b',
    facilityName: '冒険の森「パンダらんど」B',
    coords: { lat: 35.952429, lng: 136.183053 },
    radiusMeters: 100,
    checkinMethod: 'gps',
    mascotMood: 'excited',
    rarity: 'common',
    note: '敷地が広いので2点に分散のうちB地点（暫定座標）',
  },
  {
    id: 'love-bell',
    facilityName: '愛の鐘（展望台広場）',
    coords: { lat: 35.952420, lng: 136.180997 },
    radiusMeters: 40,
    checkinMethod: 'gps',
    mascotMood: 'happy',
    rarity: 'rare',
    note: '頂上のご褒美スポット。レアキャラ向き',
  },
  {
    id: 'shodo-an',
    facilityName: '茶呈「松堂庵」',
    coords: null,
    radiusMeters: 40,
    checkinMethod: 'qr_gps',
    mascotMood: 'welcome',
    rarity: 'common',
    note: '座標未確定。鯖江市公園緑地課へ問い合わせ予定（0778-53-2239）',
  },
]

export const SPAWN_POINT_GROUPS: SpawnPointGroup[] = [
  { facilityNo: 1, facilityName: '西山動物園', points: SPAWN_POINTS.filter((p) => p.id.startsWith('zoo-')) },
  { facilityNo: 2, facilityName: '道の駅西山公園', points: SPAWN_POINTS.filter((p) => p.id === 'roadside-station') },
  { facilityNo: 3, facilityName: '芝生広場（お祭り広場）', points: SPAWN_POINTS.filter((p) => p.id.startsWith('lawn-plaza-')) },
  { facilityNo: 4, facilityName: '結びの広場（結びのチャイム）', points: SPAWN_POINTS.filter((p) => p.id === 'musubi-hiroba') },
  { facilityNo: 5, facilityName: '大噴水', points: SPAWN_POINTS.filter((p) => p.id === 'fountain') },
  { facilityNo: 6, facilityName: '西山橋', points: SPAWN_POINTS.filter((p) => p.id === 'nishiyama-bridge') },
  { facilityNo: 7, facilityName: '上段の庭', points: SPAWN_POINTS.filter((p) => p.id === 'upper-garden') },
  { facilityNo: 8, facilityName: '北の庭', points: SPAWN_POINTS.filter((p) => p.id === 'north-garden') },
  { facilityNo: 9, facilityName: '冒険の森「パンダらんど」', points: SPAWN_POINTS.filter((p) => p.id.startsWith('panda-land-')) },
  { facilityNo: 10, facilityName: '愛の鐘（展望台広場）', points: SPAWN_POINTS.filter((p) => p.id === 'love-bell') },
  { facilityNo: 11, facilityName: '茶呈「松堂庵」', points: SPAWN_POINTS.filter((p) => p.id === 'shodo-an') },
]
